### ISSUE TITLE
Proto Error returned when using aetest context -- `proto: invalid UTF-8 string`

### ISSUE THREAD

**Issue by egag** [golang/appengine#136] opened 2018-05-12 18:28 UTC
The error is set inside the `Iterator` on the call to `datastore.Query.Run`.
It is initially returned by the call to `internal.Call` line 534 in `datastore/query.go`
Which returns the error at the call to `proto.Unmarshall` line 534 (also coincidently lol) in `internal/api.go`
The error is: `proto: invalid UTF-8 string`

This occurs with the most recent version of `github.com/golang/protobuf` which was updated in response to this issue: https://github.com/golang/protobuf/issues/484

The following code reproduces the issue:
```
func TestB() {
	inst, err := aetest.NewInstance(nil)
	if err != nil {
		panic(err.Error())
	}
	req, err := inst.NewRequest("GET", "/", nil)
	if err != nil {
		panic(err.Error())
	}
	ctx := appengine.NewContext(req)
	iter := datastore.NewQuery("link").KeysOnly().Run(ctx)
	_, err = iter.Cursor()
	if err != nil {
		panic(err.Error())
	}
}

**Comment by sbuss** [comment] 2018-05-17 00:28
Thank you for the bug report, I can reproduce this. This appears to be due to https://github.com/golang/protobuf/pull/499, which changes how the protobuf library handles strings: they are now expected to be valid UTF-8 strings.

Unfortunately, the way we encode protos in other protos in the datastore library doesn't produce valid UTF-8 strings.

**Comment by sbuss** [comment] 2018-05-17 00:31
This is also the reason our tests on Travis just started failing.

**Comment by egag** [comment] 2018-05-17 14:38
Thanks for getting back to me on this, @sbuss!

As a temporary resolution, I have added this to our deploy scripts ```pushd ${GOPATH}/src/github.com/golang/protobuf/ && git checkout ac606b176499 && popd

**Comment by dsnet** [comment] 2018-05-22 21:39
I'm not familiar with data store, but IIUC, it is the user who provides the proto message that is to be marshaled and unmarshaled.

For your use-case, are you able to switch the proto field type from `string` to `bytes`?

**Comment by dsnet** [comment] 2018-05-22 22:43
I just  merged golang/protobuf#616, which should help identify which field is problematic.

**Comment by sbuss** [comment] 2018-05-22 22:55
Thanks, @dsnet. The error is now:

`main_test.go:24: testB: proto: string field "appengine.CompiledQuery.PrimaryScan.index_name" contains invalid UTF-8`

**Comment by dsnet** [comment] 2018-05-23 17:40
Is that a field where the proto type can be easily switch from `string` to `bytes`?

**Comment by sbuss** [comment] 2018-05-25 00:42
I have been experimenting with fixing this, and it looks like just replacing `query.Encode()` with any arbitrary string might be the right solution.

@egag Can you try this?

```sh
pushd $(dirname $(which gcloud))/../platform/google_appengine/google/appengine/datastore
sed -i "s/query.Encode()/devindex/" datastore_stub_util.py
popd
go get -u github.com/golang/protobuf
```

I'm not 100% sure that this will work, but I'd like to get feedback from a real-world use case.

**Comment by egag** [comment] 2018-05-25 15:33
@sbuss This did not fix it for me.

Unfortunately, I get this error:
`proto: string field "appengine.PropertyValue.StringValue" contains invalid UTF-8`

Is this happening because of a particular field on the query?

**Comment by lukebjerring** [comment] 2018-05-25 15:42
I'm also seeing `proto: string field "appengine.CompiledQuery.PrimaryScan.index_name" contains invalid UTF-8` inside my Docker image (`FROM gcr.io/gcp-runtimes/go1-builder:1.10`), but the error does not occur outside Docker (on both macOS and Linux).

Anyone know what aetest and/or dev_appserver.py will be missing in terms of environment that will make the difference? I tried this:

    RUN apt-get install -y locales
    RUN locale-gen en_US.UTF-8

    ENV LANG en_US.UTF-8
    ENV LANGUAGE en_US:en
    ENV PYTHONIOENCODING=UTF-8

but made no difference.

**Comment by sbuss** [comment] 2018-05-25 16:43
@egag Well, that's progress :) I'm pretty sure that if you use #141 the error will disappear:

```sh
pushd $GOPATH/src/github.com/golang/appengine && git fetch && git checkout fixdatastore && popd
```

If that's the case, then that's going to make fixing it in prod a little more difficult for me, but at least I'll know for sure that that's the right approach.

**Comment by sbuss** [comment] 2018-05-25 16:50
@lukebjerring I think that's happening because your system's `github.com/golang/protobuf`is out of date, but the docker image is using the latest protobuf package.

The error message does make it sound like it's a locale issue, but it's actually because `protobuf` started validating all `string` fields to be valid `UTF-8`, which an encoded `protobuf` message cast to a string is not.

**Comment by egag** [comment] 2018-05-25 17:07
@sbuss It seems as though that fixed the query error.
I am now getting another proto error from `datastore.Put`

But I believe this is an error on my side, it's occurring on a byte slice of a gzipped json object.

New Error: `proto: string field "appengine.PropertyValue.StringValue" contains invalid UTF-8`

```
github.com/golang/protobuf/proto.Marshal
github.com/golang/protobuf/proto/table_marshal.go:2639 +0x1cd
google.golang.org/appengine/internal.Call
google.golang.org/appengine/internal/api.go:473 +0x2a9
google.golang.org/appengine/datastore.PutMulti
google.golang.org/appengine/datastore/datastore.go:351 +0x499
google.golang.org/appengine/datastore.Put
google.golang.org/appengine/datastore/datastore.go

**Comment by egag** [comment] 2018-05-25 17:11
@sbuss I will give that a try! Sorry about it being more difficult to fix in prod. I really appreciate your help with this!

**Comment by egag** [comment] 2018-05-25 17:58
@sbuss `proto.Marshal` at line 484 in `internal/api.go` returns `proto: string field "appengine.PropertyValue.StringValue" contains invalid UTF-8` when marshaling binary data from a byte slice
the error is returned from `XXX_Marshal` at line 2625 in `github.com/golang/protobuf/proto/tablemarshal.go`

**Comment by sbuss** [comment] 2018-05-25 18:02
@egag unfortunately, you can no longer store binary data in the StringValue.

You might be doing something like this:

```
m, err := proto.Marshal(...)
```

But now you need to do this:

```
s = proto.MarshalTextString(...)
```

My biggest concern is that you've stored invalid UTF-8 strings in datastore which you'll be unable to retrieve using the latest `protobuf` package. This is one of the things I'm investigating as fallout from this change. I may have to ask the protobuf team to undo the change :\

**Comment by egag** [comment] 2018-05-25 18:36
@sbuss Interesting. That's unfortunate. Is binary data no longer supported? It's still listed in the [docs](https://cloud.google.com/appengine/docs/standard/go/datastore/entities)

Or is there a more appropriate way to store binary data than in a slice of bytes? This error is occurring when I use datastore.Put for an entity with a property of type `Data []byte` that holds the binary.

**Comment by egag** [comment] 2018-05-25 19:11
@lukebjerring try adding this to your docker file (after downloading all dependencies): 
`RUN pushd ${GOPATH}/src/github.com/golang/protobuf/ && git checkout ac606b176499 && popd`

**Comment by lukebjerring** [comment] 2018-05-25 19:33
@egag thanks, did something similar:

     go_medium_test: go_deps dev_appserver_deps
       # Hack to work around https://github.com/golang/appengine/issues/136
       cd $(GOPATH)/src/github.com/golang/protobuf; git checkout ac606b1
       cd $(WPTD_GO_PATH); go test -tags=medium -v $(FLAGS) ./...

**Comment by egag** [comment] 2018-05-25 21:09
@sbuss Great! This should reproduce the error:

```
	key := datastore.NewKey(ctx, "data", "data1", 0, nil)
	data := &struct{ Data []byte }{Data: []byte("\xa0\x01")}  // Data: []byte("abc") works fine
	_, err := datastore.Put(ctx, key, data)
	if err != nil {
		panic(err.Error())
	}
```
I think it's because the byte slice is treated as a string under the covers.

**Comment by sbuss** [comment] 2018-05-25 22:37
Thanks for that code snippet @egag! I'm closing this issue and replacing it with #143 now that the dev_appserver issue has been addressed (fix to be released in a couple weeks) and to reduce on the noise in the issue.

**Closed by sbuss** 2018-05-25 22:37 UTC

**Comment by egag** [comment] 2018-05-25 22:41
Much appreciated! For reference/if others run into this, this fixed the original issue:

```
pushd $(dirname $(which gcloud))/../platform/google_appengine/google/appengine/datastore
sed -i "s/query.Encode()/'devindex'/" datastore_stub_util.py
popd
go get -u github.com/golang/protobuf
